###############################################################################
# Copyright (c) 2020, 2025 ArSysOp and others
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0/.
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Alexander Fedorov (ArSysOp) - initial API and implementation
###############################################################################
name: Build and deploy

on:
  push:
    branches: [ not-now ]
  pull_request:
    branches: [ main ]
  workflow_call:
    inputs:
      releaseVersion:
        description: 'If this is a release build'
        required: false
        type: string

concurrency:
  group: "build"
  cancel-in-progress: true

#TODO: restrict permissions as far as possible!
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up JDK
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: 3.9.11
    - name: Build with Maven
      run: >-
        mvn clean verify
        --no-transfer-progress --batch-mode --update-snapshots
        -P baseline-check
    - name: Upload P2 repository
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: p2-repository
        path: releng/org.eclipse.passage.fls.repository/target/repository
        retention-days: 7
        if-no-files-found: error

#TODO: instead just upload the zip in the build job and decide in the deploy job where to put to repo
# And iterator over all releases and get their repo artifacts too and unzip them too.
# To keep the repo smaller, add references to stable repos. How to handle intermediate states? Maybe only add references in release builds
# TODO: with release build:
# - run the build as release commit (or just current main)
#  - let the build create a release deployment.
# See for triggering another workflow from the current workflow: https://stackoverflow.com/questions/71952762/how-to-trigger-a-workflow-from-another-workflow-using-github-actions
# - Tag the current release commit (or just current main)
# - create GH release for that tag
# - create a commit to update the README
# - create second commit to update versions to next minor
# - create a PR with both commits


  # Deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Obtain P2 repository
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: p2-repository
        path: 'snapshots/latest'
    - name: Move release
      if: ${{ inputs.releaseVersion }} 
      run: |
        #TODO: read the version from somewhere!
        mv snapshots/latest ${{ inputs.releaseVersion }}
        ls -lR
#TODO: download all other release artifacts too and arrange them
    - name: Upload Page artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: .
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
