name: Release

on:
  workflow_dispatch
#TODO: restrict permissions as far as possible (also from the job call)!
permissions: write-all
env:
  MAVEN_ARGS: '--no-transfer-progress --batch-mode'

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read-version.outputs.version }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        sparse-checkout: |
          .mvn
          releng/org.eclipse.passage.parent
    - id: read-version
      working-directory: 'releng/org.eclipse.passage.parent'
      run: |
        mvn help:evaluate -Dexpression=project.version '-Doutput=projectVersion-value.txt'
        version=$(cat projectVersion-value.txt)
        version=${version%%-SNAPSHOT}
        echo "version=${version}"
        echo "version=${version}" >> "$GITHUB_OUTPUT"

  release-build:
    uses: ./.github/workflows/build.yml
    needs: init
    with:
      releaseVersion: ${{ needs.init.outputs.version }}
    permissions: write-all

# - Tag the current release commit (or just current main)
# - create GH release for that tag
# - create a commit to update the README
# - create second commit to update versions to next minor
# - create a PR with both commits

  # Deploy job
  release:
    needs: [ release-build, init]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - run: |
        sed -i --expressions "s|"
        releaseVersion='v${{ needs.init.outputs.version }}'
        git tag -a "${releaseVersion}" -m "Release ${releaseVersion}"
        git push origin "${releaseVersion}"
        mvn help:evaluate -Dexpression=project.version '-Doutput=projectVersion-value.txt'
        